# fly.toml app configuration file generated for puhelinluettelo-frosty-haze-9 on 2024-09-26T17:32:51+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'puhelinluettelo-frosty-haze-9'
primary_region = 'cdg'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
